version: '3.8'

services:
  crm-frontend:
    image: crm-joao-avila-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://91.108.126.147:3000/api/v1
      - VITE_ADMIN_ROLENAMES=ADM,master_admin
      - VITE_TOKEN_KEY=token
    restart: unless-stopped
    networks:
      - crm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "stack.name=crm-joao-avila"
      - "stack.description=CRM João Avila Frontend"
      - "traefik.enable=true"
      - "traefik.http.routers.crm-frontend.rule=Host(`crm.localhost`)"
      - "traefik.http.services.crm-frontend.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  crm_network:
    driver: bridge
    name: crm_network
